// whoosh native paste addon · macOS implementation
//
// 行为：
//   1. 可选保存当前 NSPasteboard 的纯文本
//   2. clearContents + setString:forType:NSPasteboardTypeString
//   3. 可选附加 org.nspasteboard.ConcealedType 标记（剪贴板管理器约定，不入历史）
//   4. CGEventPost 模拟 ⌘V
//   5. dispatch_after 400ms 在 main queue 恢复原内容（仅当保存过）
//
// 注意：ARC 开启（binding.gyp xcode_settings CLANG_ENABLE_OBJC_ARC=YES），
// 所有 Cocoa 对象走 ARC，CFType 仍需手动 CFRelease。

#import <Cocoa/Cocoa.h>
#import <ApplicationServices/ApplicationServices.h>
#include <napi.h>

// HIToolbox / Carbon 的 keycode 常量，避免引入整个 Carbon framework
static const CGKeyCode kVK_Command = 0x37;
static const CGKeyCode kVK_ANSI_V  = 0x09;

// nspasteboard.org 三种标记 —— 不同剪贴板管理器尊重的子集不一样，全打上
//   ConcealedType:   敏感/机密，应当遮蔽
//   TransientType:   即将被替换/恢复，不应记录历史
//   AutoGeneratedType: 应用生成，用户无主动 Copy 意图
// 我们的场景同时属于 transient（要恢复）+ auto-generated（用户没主动 copy）
static NSString *const kConcealedType     = @"org.nspasteboard.ConcealedType";
static NSString *const kTransientType     = @"org.nspasteboard.TransientType";
static NSString *const kAutoGeneratedType = @"org.nspasteboard.AutoGeneratedType";

static void PostCommandV(void) {
    CGEventSourceRef src = CGEventSourceCreate(kCGEventSourceStateHIDSystemState);

    CGEventRef cmdDown = CGEventCreateKeyboardEvent(src, kVK_Command, true);
    CGEventPost(kCGHIDEventTap, cmdDown);
    CFRelease(cmdDown);

    CGEventRef vDown = CGEventCreateKeyboardEvent(src, kVK_ANSI_V, true);
    CGEventSetFlags(vDown, kCGEventFlagMaskCommand);
    CGEventPost(kCGHIDEventTap, vDown);
    CFRelease(vDown);

    CGEventRef vUp = CGEventCreateKeyboardEvent(src, kVK_ANSI_V, false);
    CGEventSetFlags(vUp, kCGEventFlagMaskCommand);
    CGEventPost(kCGHIDEventTap, vUp);
    CFRelease(vUp);

    CGEventRef cmdUp = CGEventCreateKeyboardEvent(src, kVK_Command, false);
    CGEventPost(kCGHIDEventTap, cmdUp);
    CFRelease(cmdUp);

    if (src) CFRelease(src);
}

static Napi::Value PasteText(const Napi::CallbackInfo& info) {
    Napi::Env env = info.Env();

    if (info.Length() < 1 || !info[0].IsString()) {
        Napi::TypeError::New(env, "pasteText: first argument must be a string").ThrowAsJavaScriptException();
        return env.Undefined();
    }

    std::string utf8 = info[0].As<Napi::String>().Utf8Value();

    bool preserveClipboard = true;
    bool markTransient = true;
    if (info.Length() >= 2 && info[1].IsObject()) {
        Napi::Object opts = info[1].As<Napi::Object>();
        if (opts.Has("preserveClipboard")) preserveClipboard = opts.Get("preserveClipboard").ToBoolean();
        if (opts.Has("markTransient"))    markTransient    = opts.Get("markTransient").ToBoolean();
    }

    @autoreleasepool {
        NSPasteboard *pb = [NSPasteboard generalPasteboard];

        // 1) 保存原文本
        NSString *original = nil;
        if (preserveClipboard) {
            original = [pb stringForType:NSPasteboardTypeString];
        }

        // 2) 写新内容 + 标记
        NSString *nsText = [NSString stringWithUTF8String:utf8.c_str()];
        if (nsText == nil) {
            // UTF-8 解码失败兜底
            return env.Undefined();
        }

        NSMutableArray<NSPasteboardType> *types = [NSMutableArray array];
        [types addObject:NSPasteboardTypeString];
        if (markTransient) {
            [types addObject:kConcealedType];
            [types addObject:kTransientType];
            [types addObject:kAutoGeneratedType];
        }

        [pb clearContents];
        [pb declareTypes:types owner:nil];
        [pb setString:nsText forType:NSPasteboardTypeString];
        if (markTransient) {
            // 三种标记的 data 内容不重要，type 存在即生效（剪贴板管理器扫 type 列表）
            [pb setData:[NSData data] forType:kConcealedType];
            [pb setData:[NSData data] forType:kTransientType];
            [pb setData:[NSData data] forType:kAutoGeneratedType];
        }

        // 3) 模拟 ⌘V
        PostCommandV();

        // 4) 异步恢复
        //
        // 延迟下限来自：CGEventPost 是异步入 HID 队列，目标 app 下个 run loop tick (<16ms)
        // 才处理 ⌘V，处理时才读 NSPasteboard。100ms 留足缓冲让目标 app 完成读取。
        //
        // 延迟上限来自：希望溜过轮询型剪贴板管理器（Raycast 等估计 100-200ms poll interval），
        // 越短越容易在它两次 poll 之间完成恢复，让它只观察到原文本。
        // 事件订阅型（KVO changeCount）则与延迟无关，那只能靠字符注入彻底绕开剪贴板。
        if (preserveClipboard && original != nil) {
            NSString *toRestore = [original copy];
            dispatch_after(
                dispatch_time(DISPATCH_TIME_NOW, (int64_t)(0.1 * NSEC_PER_SEC)),
                dispatch_get_main_queue(),
                ^{
                    NSPasteboard *p = [NSPasteboard generalPasteboard];
                    [p clearContents];
                    [p declareTypes:@[NSPasteboardTypeString] owner:nil];
                    [p setString:toRestore forType:NSPasteboardTypeString];
                }
            );
        }
    }

    return env.Undefined();
}

static Napi::Object Init(Napi::Env env, Napi::Object exports) {
    exports.Set("pasteText", Napi::Function::New(env, PasteText));
    return exports;
}

NODE_API_MODULE(paste, Init)
